### ISSUE TITLE
Нету кнопки после загрузки

### ISSUE THREAD

**Issue by linfo** [Kron4ek/minecraft-vortex-launcher#1]
Хотелось бы видеть кнопку "ОК" или нечто подобное после полной загрузки игры.
![1](https://user-images.githubusercontent.com/751693/57136889-d9610380-6db6-11e9-9a29-49a5a00c5415.png)

**Comment by Kron4ek** [comment]
Хорошо, сделаю.

**Comment by Kron4ek** [comment]
Вот так нормально будет?

![Снимок экрана от 2019-05-04 16-28-43](https://user-images.githubusercontent.com/13851877/57178473-fb778600-6e89-11e9-8ded-b2c78c2946f3.png)

**Comment by linfo** [comment]
да, для пользовотеля это более логично. Нажимает "ОК" и окно закрывается. И крести лучше убрать, чтобы пользователь случно не закрыл окно прогресса.

**Comment by Kron4ek** [comment]
Хорошо. Но крестик, увы, не получится убрать.

> чтобы пользователь случно не закрыл окно прогресса.

Об этом я позаботился. Можешь попробовать закрыть окно во время загрузки - не получится.

**Comment by linfo** [comment]
тогда все, эту проблему можно закрывать как решенную.
