### ISSUE TITLE
Possible to install Forge and Fabric on Linux?

### ISSUE THREAD

**Issue by Radagast** [Kron4ek/minecraft-vortex-launcher#10]
As the title. 

Thanks

**Comment by Kron4ek** [comment]
Yes, if you install them separately. Fabric on top of Forge doesn't work yet (both on Windows and on Linux).
---
Да, если установить их раздельно. Fabric поверх Forge на данный момент не работает (как на Windows, так на Linux).

p.s. Можно на русском общаться, если есть возможнось.
