### ISSUE TITLE
Incorrect default Java path on Windows

### ISSUE THREAD

**Issue by La1eon** [Kron4ek/minecraft-vortex-launcher#11]
When you look at the `javaBinaryPathDefault` variable, you can see that its initial state on Windows is `C:\jre8\bin\javaw.exe`, while the real default Java 8 path on Windows is `C:\Program Files\Java\jre1.8.0_<e.g._221_for_Java_8u221>\bin\<chosen_Java_binary>`.

If it is done on purpose, because e.g. you have Java in such path, feel free to close this issue. But if not, it would be nice if you could change the initial state of the variable to the real default path.

**Comment by Kron4ek** [comment]
This variable is only used when "Use custom Java" option is enabled, and the default value is just an example.

**Comment by La1eon** [comment]
Thanks for the explanation. If you have any questions or thoughts about my other "issues", feel free to share them with me. I'll answer them in my free time :)
