### ISSUE TITLE
[Feature Request] Support for launcher translations

### ISSUE THREAD

**Issue by La1eon** [Kron4ek/minecraft-vortex-launcher#12]
Currently this launcher uses hard-coded English strings, so it's impossible to have the GUI in other language without modifying the source code, and recompiling it on one's own.

It would be great if you could create on GitHub a directory for translation files, and add to it a reference, `en-us.json` (or `en_us.json`) or similar file. Then translators (I'm willing :) ) would be able to modify its name (to e.g. `de-de.json` (or `de_de.json`) and half of its content, and submit this file via pull request. You would then contain all the translation files (including the `en-us.json` file) into the launcher executable file (.exe on Windows, something other on Linux and macOS). At the end all users would have an ability to select their preferred language via e.g. dropdown menu in the launcher settings window.

I have seen a lot of Minecraft launchers do this in such a way, but I don't know whether it is possible or not in case of this launcher, since all source code is contained in only one file for every OS.

**Comment by Kron4ek** [comment]
Sorry, but i don't think it makes sense to add that feature at the current launcher state. The launcher has so little amount of text, i don't think someone will have issues with that even with low or non-existent knowledge of english language.
