### ISSUE TITLE
При открытии списка

### ISSUE THREAD

**Issue by linfo** [Kron4ek/minecraft-vortex-launcher#2]
При открытии списка вылезает вот такой столбец
![Screenshot_20190503_152058](https://user-images.githubusercontent.com/751693/57136988-2e9d1500-6db7-11e9-83d7-e039154e4025.png)

**Comment by Kron4ek** [comment]
Да, я тоже заметил. Это похоже на баг (или особенность?) того, как PureBasic строит выдвижные списки, используя GTK. Но я помотрю, что можно сделать, может и получится найти решение.

На Windows такого нет, так что это точно как-то связано с GTK.

**Comment by linfo** [comment]
У меня KDE, возможно особенность трансляции GTK.

**Comment by Kron4ek** [comment]
Да не, у меня на Xfce так же. Что интересно, если пролистать вниз, чтобы пустое пространство исчезло, а потом подняться снова вверх, то его уже не будет.

**Comment by linfo** [comment]
Да, подтверждаю, возможно из-за величины списка?
Так как другое выпадающее меню работает корректно. Возможно есть способ ограничить список, чтобы появлялась прокрутка?

**Comment by Kron4ek** [comment]
Да, это из-за величины списка, с короткими списками такого вроде не возникает.

> Возможно есть способ ограничить список, чтобы появлялась прокрутка?
Насколько я знаю, нет. Я нашел костыльное решение в виде выбора по умолчанию версии где-нибудь в центре списка, но меня такое решение не устраивает. Буду думать дальше.

**Comment by linfo** [comment]
ахаха, т.е. мяу )

**Comment by Kron4ek** [comment]
Я пока закрою этот репорт, так как возможности исправить это все равно нет.
