### ISSUE TITLE
Where are saves folder?

### ISSUE THREAD

**Issue by playerro** [Kron4ek/minecraft-vortex-launcher#20]
Hello! Suddenly my world doesnt show in single player worlds, I want to revive it from last save, but can't find saves folder. Where does it located in this launcher?

**Comment by Kron4ek** [comment]
Hello. If the path to the game folder doesn't contain spaces, then saves folder is located inside the game folder.

**Comment by playerro** [comment]
Phew! 
Opened latest .log file and found the path to save folder and found exception message " Not in GZIP format
	at java.util.zip.GZIPInputStream.readHeader(Unknown Source) ~[?:1.8.0_121]
"
Thank you for help, now I will try to do something with this to save my world :(

**Comment by Kron4ek** [comment]
Seems like your save file somehow got corrupted. I'm not sure this can be fixed, unless you have backup.
