### ISSUE TITLE
Установщик версий не видит сеть на Windows XP

### ISSUE THREAD

**Issue by Vasya2008cat** [Kron4ek/minecraft-vortex-launcher#28]
![minecraft](https://user-images.githubusercontent.com/76242721/133311067-3b270a09-e2e5-4fc8-a873-2defef683e5f.PNG)

**Comment by Kron4ek** [comment]
На Windows XP почему-то не работают https соединения в PureBasic. Я прикрепил версию, в которой заменил https на http во всех URL.

[VLauncher_1.1.15_WinXP.exe.zip](https://github.com/Kron4ek/minecraft-vortex-launcher/files/7164822/VLauncher_1.1.15_WinXP.exe.zip)

**Comment by Vort** [comment]
> это должно исправить проблему с соединением на Windows XP.

К сожалению, не работает. Файлы качает, но с мусором:
`<?xml version="1.0" encoding="utf-8"?><Error><Code>AccountRequiresHttps</Code><Message>The account being accessed does not support http.
RequestId:39f53fdf-901e-0063-0717-2a729c000000
Time:2025-09-20T10:16:53.1275947Z</Message><AccountName>librariesminecraftnet</AccountName></Error>`
Придётся искать альтернативный метод закачки...
