### ISSUE TITLE
проблема после установки Forge 

### ISSUE THREAD

**Issue by linfo** [Kron4ek/minecraft-vortex-launcher#3]
после установки Forge весь список установленных версий игры пропадает
![Screenshot_20190504_165034](https://user-images.githubusercontent.com/751693/57180007-c3257700-6e8c-11e9-86d1-d2daaa829904.png)
![Screenshot_20190504_165013](https://user-images.githubusercontent.com/751693/57180008-c3257700-6e8c-11e9-903e-91d8de73609c.png)
![Screenshot_20190504_165121](https://user-images.githubusercontent.com/751693/57180016-dfc1af00-6e8c-11e9-8a6d-7bf79ee5a898.png)
хотя в файле vortex_launcher.conf все прописано

**Comment by Kron4ek** [comment]
Сейчас попробую у себя воспроизвести проблему.

**Comment by Kron4ek** [comment]
А если убрать из каталога versions файлы ".jar" и ".log"?
