### ISSUE TITLE
Wont work with 1.18 fabric loader

### ISSUE THREAD

**Issue by Dragan146** [Kron4ek/minecraft-vortex-launcher#32]
OpenJDK Runtime Environment (build 17.0.1+12-39)
OpenJDK 64-Bit Server VM (build 17.0.1+12-39, mixed mode, sharing)
Error: Could not find or load main class net.fabricmc.loader.impl.launch.knot.KnotClient
Caused by: java.lang.ClassNotFoundException: net.fabricmc.loader.impl.launch.knot.KnotClient

**Comment by Kron4ek** [comment]
You need to enable "Download missing libraries on game start" in the launcher settings.
