### ISSUE TITLE
[Suggestion] Skin changing

### ISSUE THREAD

**Issue by Mak992** [Kron4ek/minecraft-vortex-launcher#38]
I am wondering about feature to change skin, is it possible?

**Comment by Kron4ek** [comment]
You mean locally so that only you could see a changed skin or globaly so other players could see it? If the latter, it is probably possible, but i have no knowledge on how to properly implement such system.

**Comment by Mak992** [comment]
I meant online, but thanks for answer

**Comment by cgarz** [comment]
Skins are tied to your minecraft.net account iirc.
I think in order for others to also see it without setting it at minecraft.net everyone needs to be using alternative minecraft online services, such as mineshafter.
