### ISSUE TITLE
How to add Minecraft versions to launcher? Doens`t seem to work.

### ISSUE THREAD

**Issue by necros2k7** [Kron4ek/minecraft-vortex-launcher#4]
Copied 19w02a, 1.12.2forge to Versions folder, nothing happens after launch (
1.14 runs fine
(jre 1.8.0.172 )

**Comment by Kron4ek** [comment]
More proper way is to download versions using "Downloader" in launcher (for example, you can download 19w02a from there). But if you want to add versions by copying them into verisons folder then it's also necessary to copy libraries folder, or you can enable "Downloading missing libraries" in launcher settings and that may help.

p.s. Если хочешь, можно на русском писать.

**Comment by sonofthesnow** [comment]
а как по поводу 1.14.1 pre_1-2, они не работают на данный момент

**Comment by Kron4ek** [comment]
> а как по поводу 1.14.1 pre_1-2, они не работают на данный момент

Какая версия лаунчера? На 1.1.3 работают, я проверял.

**Comment by sonofthesnow** [comment]
оп понял, сори, версия 1.1.01, друг скачал с торрента просто такую, как скачать последнюю? :D

**Comment by Kron4ek** [comment]
Со страницы [Releases](https://github.com/Kron4ek/minecraft-vortex-launcher/releases) можно скачать. Ну и можно подписаться

**Comment by sonofthesnow** [comment]
спасибо! мне не нужно у меня лицензия, а друг на гитхабе не зарегистрирован просто, вот
