### ISSUE TITLE
Download failed and Download error happens tons of times but the internet is fine

### ISSUE THREAD

**Issue by RDKRACZ** [Kron4ek/minecraft-vortex-launcher#40]
I have these errors every time I download a Minecraft release, on two different Linux distributions. It makes downloading really painful. 100% sure it's not my internet since I reproduced it many times.
![image](https://user-images.githubusercontent.com/43277609/152609738-2efae6c5-5cd8-4860-a812-33fabd1000dd.png)
![image](https://user-images.githubusercontent.com/43277609/152609940-cfcb6e84-c360-4d92-a798-976b5761be46.png)

**Comment by Kron4ek** [comment]
Does the launcher always show "1546 files left" or the number is different each time? Also, on which Linux distros did you reproduce this problem?

**Comment by RDKRACZ** [comment]
>on which Linux distros did you reproduce this problem?

Clear Linux and Mageia, both with Gnome. I also have OpenMandriva installed and can test on it later today.

> i suggest to try to download the client later, just in case.

The issue was happening for a few days.

> Does the launcher always show "1546 files left" or the number is different each time

Depends, it's mainly different - sometimes the download fails half a minute later and sometimes the next second I start it so a few times it was the same.

**Comment by Kron4ek** [comment]
I can't reproduce the issue on Mageia, don't know why it happens for you.

**Comment by Kron4ek** [comment]
Try this launcher build.

[VLauncher_test_x64_Linux.zip](https://github.com/Kron4ek/minecraft-vortex-launcher/files/8008344/VLauncher_test_x64_Linux.zip)

**Comment by RDKRACZ** [comment]
I started pinging the address, then run both launchers (the one I already had for a few days and the one you linked above) and despite 0% packet loss both of them failed around 2600 files left do download mark. **It did not happened at the same time.**

Then I closed the launchers and started them again. One of them failed about a minute later and **when I wanted to retry downloading on this instance it said I don't have an internet connection despite the second instance downloading just fine.**

**Comment by RJmsG** [comment]
I have a problem like this on windows. Except, it doesn't say anything about the internet. I tried multiple launcher versions.
