### ISSUE TITLE
1.1.17 Malware?

### ISSUE THREAD

**Issue by bongmixtape** [Kron4ek/minecraft-vortex-launcher#41]
Newest version (1.1.17) gets blocked by Windows Defender SmartScreen.

Additionally the app gets flagged as malicious on [VirusTotal](https://www.virustotal.com/gui/file/c0e82b0b884099dee5676d880205b6d7af36f15fbb817b2fb594609c606120a4) 3 times:
- MaxSecure - Trojan.Malware.300983.susgen
- SecureAge APEX - Malicious
- VBA32 - BScope.TrojanSpy.SpyEyes

**Comment by Kron4ek** [comment]
There is no malware my launcher, you can examine the source code yourself. As for binaries, some antiviruses always identify executables compiled with PureBasic as malware. Even a very simple program like:

```
MessageRequester("Test Window", "Hello World")
```
is idenfied as malware, and more compilcated programs get more detections.

I can do nothing about that.
