### ISSUE TITLE
How to build it?

### ISSUE THREAD

**Issue by RDKRACZ** [Kron4ek/minecraft-vortex-launcher#42]
I know nothing about PureBasic and I only have little knowledge about the make, CMake, etc. How can I build it in other to make it work on Void Linux?

**Comment by Kron4ek** [comment]
You need to download PureBasic, install build dependencies (at least gcc and gtk3-devel), after that launch PureBasic IDE, open a source code file you want to compile and compile it (choose Compiler -> Create Executable at the top menu).

And before compilation go to Compiler -> Compiler Options and set the "Create threadsafe executable" option. This is important. 

Note that PureBasic is non-free. The demo version is free, but it does not allow to compile files with more than ~800 lines of code. You can, however, find a "full free" version on the internet if you know what i mean.
