### ISSUE TITLE
Can't join servers.

### ISSUE THREAD

**Issue by RJmsG** [Kron4ek/minecraft-vortex-launcher#43]
I don't know if this has already been answered, but I can't join servers. I know I could, because of the Log4J issue, but I can't for some reason.

It says that it's an invalid session.

Thank you, RJG.

**Comment by Kron4ek** [comment]
Hi, the "Invalid session" error means that this server is only available for players who have bought the game and are logged into their Microsoft account. You need to find servers that allow anyone to enter, they do exist they just harder to find.

If you are running your own server, you need to set online-mode to false in the server.properties file.
