### ISSUE TITLE
What string do you use to start minecraft?

### ISSUE THREAD

**Issue by YaricKingPro** [Kron4ek/minecraft-vortex-launcher#45]
What string do you use to start minecraft?

**Comment by Kron4ek** [comment]
The string is generated dynamically by parsing the client json file. If you want to see how does it look exactly, you can enable "Save launch string to file" in the launcher settings.

**Comment by YaricKingPro** [comment]
> Строка генерируется динамически путем разбора json-файла клиента и выглядит по-разному для каждой версии игры. Если вы хотите увидеть, как именно это выглядит, вы можете включить "Сохранить строку запуска в файл" в настройках лаунчера и запустить игру, строка будет в файле launch_string.txt.

Thanks
