### ISSUE TITLE
LWJGL error on all Minecraft versions since Snapshot_22w16a and up

### ISSUE THREAD

**Issue by nyankrauss** [Kron4ek/minecraft-vortex-launcher#47]
According to Technical Changes in 22w16a in Patch notes from April 20:
Mojang updated LWJGL library to version 3.3.1.

Since then all next snapshots, pre-releases (and possibly releases too) stopped working.
22w15a and all previous versions are still launch and work just fine.

short first launch log file with error:
[22w16a.log](https://github.com/Kron4ek/minecraft-vortex-launcher/files/8773339/22w16a.log)

**Comment by Kron4ek** [comment]
Thanks for the bugreport. I uploaded a new launcher version, the issue should be fixed now.

**Comment by nyankrauss** [comment]
Amazing speed! 

Tested with JDK18 installed:  versions 1.13.2  -  1.18.2 works fine,
1.12.2 and earlier  -  works with custom java8 setup in options

**Comment by Kron4ek** [comment]
What about 1.19-pre3, does it work for you with the new launcher version?

**Comment by nyankrauss** [comment]
Yes, works fine! \o.o/
![2022-05-26_15 45 55](https://user-images.githubusercontent.com/106260777/170490605-cd2ac095-6d26-4764-9ceb-1c6beaa16338.png)

**Comment by Kron4ek** [comment]
Good :)
