### ISSUE TITLE
can't run game even installed Java

### ISSUE THREAD

**Issue by Miho1254** [Kron4ek/minecraft-vortex-launcher#48]
LOGS:
`Unrecognized VM option 'UseConcMarkSweepGC'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
[minecraft_linux] ❱❱❱ openjdk version "18.0.1.1" 2022-04-22
OpenJDK Runtime Environment (build 18.0.1.1+2)
OpenJDK 64-Bit Server VM (build 18.0.1.1+2, mixed mode)
`
can some one help me

**Comment by Kron4ek** [comment]
Hello,

What game version are you trying to run? For old game versions (1.12.2 and older) you need to use old Java (Java 8).

**Comment by Miho1254** [comment]
> Hello,
> 
> What game version are you trying to run? For old game versions (1.12.2 and older) you need to use old Java (Java 8).

oh thanks that solved my problem
