### ISSUE TITLE
How install mod Iris?

### ISSUE THREAD

**Issue by Geromo94** [Kron4ek/minecraft-vortex-launcher#52]
Hello. I try install mod Iris, select game folder and mod not working :C

**Comment by Kron4ek** [comment]
Hello. Here is how to get Iris working:

1. Install [Fabric Loader](https://fabricmc.net/use/installer/) to the game folder
2. Download [Sodium](https://github.com/CaffeineMC/sodium-fabric) and [Iris](https://github.com/IrisShaders/Iris/releases) (.jar files) and put them to the mods folder
3. In VLauncher select fabric-loader and run it
