### ISSUE TITLE
Forge not working

### ISSUE THREAD

**Issue by dpery** [Kron4ek/minecraft-vortex-launcher#58]
i tried install forge and it says that the installation is complete, but it just doesnt open

**Comment by Kron4ek** [comment]
I just tried Forge 43.1.3 for Minecraft 1.19.2 and it works fine for me. Make you have "Download missing libraries on game  start" enabled in the launcher settings. Also, what game version are you using and what Forge version are you trying to run?

**Comment by Kron4ek** [comment]
So after Forge installation in the launcher you choose "1.19.2-forge-43.1.3", press "Play" and then just nothing happens, right? Are there any logs or crash-reports in the game directory?

**Comment by dpery** [comment]
yes thats it basically and here are the latest report 
[latest.log](https://github.com/Kron4ek/minecraft-vortex-launcher/files/9456397/latest.log)

**Comment by Kron4ek** [comment]
Unfortunately, the log is very small and doesn't contain any errors. Could you try an older Forge version (for example, 43.0.5)?

**Comment by dpery** [comment]
i did but same it just wont open i also tried with the latest forge for 1.18.2 and same results

**Comment by Kron4ek** [comment]
That's odd, i can't reproduce the issue, i tried on Linux and on Windows 10. You can try to download the client in a new clean folder. By the way, is the vanilla version working fine for you? And how much memory do you allocate for the game?
