### ISSUE TITLE
Any progress on macOS?

### ISSUE THREAD

**Issue by egeesin** [Kron4ek/minecraft-vortex-launcher#6]
Is there any possibility to be able to open Vortex Launcher in macOS? Thanks in advance.

**Comment by Kron4ek** [comment]
Yes, i suppose it's totally possible to make the launcher work correctly on MacOS after some changes.

I will try to do that when i'll have spare time, and if everything goes well i will upload MacOS version of the launcher.

**Comment by Kron4ek** [comment]
Could you please test this versions?

[vlauncher_macos_test.app.zip](https://github.com/Kron4ek/minecraft-vortex-launcher/files/3550161/vlauncher_macos_test.app.zip)

**Comment by Kron4ek** [comment]
Could you please test this attached launcher version? My virtual machine doesn't have proper OpenGL support, so i can't test if the launcher can run the game.

[vlauncher_test_macos.app.zip](https://github.com/Kron4ek/minecraft-vortex-launcher/files/3550214/vlauncher_test_macos.app.zip)

**Comment by egeesin** [comment]
The launcher opens just fine but when I try to download (Downloader > Download) any version gives "Download Error" and says "Seems like you have no internet connection!" even though I'm on Wi-Fi. Tried to close and open Wi-Fi but still unchanged.
Also quitting launcher from menu bar or ⌘+Q not working. You can only quit by closing the window.

**Comment by Kron4ek** [comment]
Thanks for the feedback. What macOS version do you use? Download works fine for me on High Sierra (via virtual machine), i'm on ethernet though.

**Comment by egeesin** [comment]
I'm using macOS 10.14.3 version on rMBP 2015 13".

**Comment by Kron4ek** [comment]
Ok, i will setup macOS 10.14 then and i'll try to reproduce and solve your issue.

**Comment by Kron4ek** [comment]
I was able to reproduce your problem. For some reason binary compiled on High Sierra doesn't properly work on Mojave.

Here is another version of the launcher, downloading should work fine with it. But there is a bug (seems like a comiler bug) with showing progress (it updates only when focus and then unfocus window).

[vlauncher_macos_test_2.app.zip](https://github.com/Kron4ek/minecraft-vortex-launcher/files/3587501/vlauncher_macos_test_2.app.zip)

**Comment by Kron4ek** [comment]
[vlauncher_macos_test_2.app.zip](https://github.com/Kron4ek/minecraft-vortex-launcher/files/3587520/vlauncher_macos_test_2.app.zip)

**Comment by Kron4ek** [comment]
[vlauncher_macos_test_2.zip](https://github.com/Kron4ek/minecraft-vortex-launcher/files/3587521/vlauncher_macos_test_2.zip)

**Comment by Kron4ek** [comment]
I found out that download doesn't work for me too when i download launcher from the internet using browser, but it works fine when i compile launcher myself. Seems like macOS quirk (or some security measure?).

Try this another launcher version with some additional fixes. Download should work fine on it, but there is a bug with showing download progress (it updates only when focus/unfocus window).

[vlauncher_macos_test_2.zip](https://github.com/Kron4ek/minecraft-vortex-launcher/files/3587522/vlauncher_macos_test_2.zip)

**Comment by egeesin** [comment]
Alright, downloader works properly this time. Only non-critical issue is, download bar doesn't show exact progress and doesn't show remaining files yet. The bar is almost full although the game files not started to download yet.

After installation, 1.14.4 successfully launched and playable. I surprised that the launcher haven't ask for Java executable. It was already installed in my system before. Thanks for the support, expecting a release version! (as a .app bundle, maybe?) Closing this for now!

**Comment by Kron4ek** [comment]
Yes, there is bug with download progress bar, but i don't know how to fix it yet. What's interesting is that progress bar works fine on macOS High Sierra, but it doesn't work on Mojave.

> After installation, 1.14.4 successfully launched and playable.

That's good. Please also check 1.12.2 and 1.7.10 versions, if it's not too much trouble.

> as a .app bundle, maybe?

Yes, app bundle format is more convenient, but for some reason it has aforementioned issue with write access, so downloader doesn't work with it. If i figure out how to fix this, i will release launcher in app bundle format.

**Comment by egeesin** [comment]
Tested the latest commit and took some notes below: (Sorted by priority)
- 1.7.10 and 1.12.2 downloaded but didn't launched. (1.14.4 is still fine.)
- User folders such as ``resourcepacks``, ``saves`` and ``options.txt`` file not in the correct path and it creates ``~/Library/Application`` folder.
  - Intended target directory (if I am correct): ``~/Library/Application Support/minecraft_vlauncher``
  - Created this directory: ``~/Library/Application``
- App icon is blank (but not in dialog boxes) Maybe it's because of the file extension, you can try to generate and use .icns instead of .png
- Progress bar only updates if you focus any window.

**Comment by Kron4ek** [comment]
Thanks for testing, i will try fix these bugs. I removed 1.1.9 release for macOS for now, but i will upload fixed version later.

**Comment by Kron4ek** [comment]
Could you please check if 1.12.2 and 1.7.10 versions work for you without -XstartOnFirstThread parameter? You can remove it in launcher settings (enable "Use custom launch parameters" and remove -XstartOnFirstThread).

**Comment by egeesin** [comment]
With -XstartOnFirstThread parameter, MC 1.12.2 looks like this:
<img width="1280" alt="Screen Shot 2019-09-15 at 14 58 39" src="https://user-images.githubusercontent.com/8004972/64921287-09d79600-d7ca-11e9-9e56-452321173ff1.png">
But the game window is unmovable, can't click buttons, also if I tried to close it with ⌘-Q, the java process still remains and managed to kill it with Activity Monitor.

**Comment by Kron4ek** [comment]
I'm not sure that this issue is related to launcher. I think that might be related to Java version, so you can try OpenJDK 8 (or Oracle JRE 8). And also you can try to enable fullscreen (F11 key).

But to be sure if it's related to launcher or not, you can try to download and run 1.12.2 version using official Minecraft launcher, it allows to download client and play in demo mode for free. Official Minecraft launcher uses Java 8.
