### ISSUE TITLE
mods not loading with 1.7.10

### ISSUE THREAD

**Issue by Musickiller** [Kron4ek/minecraft-vortex-launcher#61]
Ok, a bit more testing helped. Mods are loading fine with 1.12.., but not with 1.7.10, will check that forge is installed correctly etc, but I was sure that it is o_O

Kinds Regards,

**Comment by Kron4ek** [comment]
Mods do work fine for me on 1.7.10 + Forge, so it's probably a misconfiguration on your side.

**Comment by Musickiller** [comment]
thanks for testing! I'll post here if I find the cause, but I think it's safe to close the issue.

**Comment by Musickiller** [comment]
Damn, I forgot to write here the fix.. I think it was Java version issue or something like that. Not launcher's issue at all. Launcher actually helped solving it =)
