### ISSUE TITLE
Could not load icon

### ISSUE THREAD

**Issue by moresavanyu** [Kron4ek/minecraft-vortex-launcher#62]
Hello,

try to run the minecraft 1.19.3 and getting the following crash report:

Time: 2022-12-19 09:04:21
Description: Initializing game

java.lang.IllegalStateException: Could not load icon: Image not of any known type, or corrupt
	at edh.a(SourceFile:162)
	at ejf.<init>(SourceFile:497)
	at net.minecraft.client.main.Main.a(SourceFile:205)
	at net.minecraft.client.main.Main.main(SourceFile:51)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at edh.a(SourceFile:162)
	at ejf.<init>(SourceFile:497)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.a(SourceFile:205)
	at net.minecraft.client.main.Main.main(SourceFile:51)
What could be the problem?

**Comment by Kron4ek** [comment]
This means your game files are corruped or incomplete. Try to redownload the game in a new clean folder.

**Comment by moresavanyu** [comment]
Done, but got the same error :(

**Comment by Kron4ek** [comment]
Do you have file `assets/objects/bd/bdf48ef6b5d0d23bbb02e17d04865216179f510a`? It should be a png icon.

**Comment by Kron4ek** [comment]
Ok, i managed to reprodouce the issue, will try to fix it.

**Comment by Kron4ek** [comment]
I uploaded a new launcher version, the issue should be fixed now. You'll need to redownload the game again, with the new launcher version this time.
