### ISSUE TITLE
Firefox blocks download, saying Vlauncher is a malware

### ISSUE THREAD

**Issue by nyankrauss** [Kron4ek/minecraft-vortex-launcher#65]
Latest Firefox (109) by default began blocking downloads of this launcher, saying it contains a malware or a virus.
Not an issue, but maybe it can be fixed by Mozilla developers, whitelisting this app, new folks who have found this launcher - would just trust firefox and skip download :c
![firefox_triggered](https://user-images.githubusercontent.com/106260777/213973485-8d5d3151-6d51-4cd8-9fc6-6f716791b2d6.png)

**Comment by Kron4ek** [comment]
This is sad, but there is nothing i can do about it. As far as i know, Firefox uses Google’s Safe Browsing to check for malware, so it even might be not a Firefox issue.

**Comment by nyankrauss** [comment]
:'3
