### ISSUE TITLE
v1.1.19 windows exe is labeled as a virus

### ISSUE THREAD

**Issue by Doodlinka** [Kron4ek/minecraft-vortex-launcher#75]
Firefox warned me about malware when downloading, and https://www.fortiguard.com/faq/onlinescanner found the file's hash in its database

**Comment by Kron4ek** [comment]
Already discussed [here](https://github.com/Kron4ek/minecraft-vortex-launcher/issues/41) and [here](https://github.com/Kron4ek/minecraft-vortex-launcher/issues/65). There is nothing i can do about that.

**Comment by Doodlinka** [comment]
You might want to add that to the readme and refer people to virustotal or something (i got 16/67)

**Comment by Doodlinka** [comment]
and to countless posts about purebasic false positives

**Comment by Doodlinka** [comment]
sorry to have borthered, should've checked for duplicate first
