### ISSUE TITLE
Vlauncher won't work on Linux Mint 21.1 Cinnamon 64-bit

### ISSUE THREAD

**Issue by 0xPascal** [Kron4ek/minecraft-vortex-launcher#77]
I downloaded the latest release of the launcher to a fresh install of Linux Mint and enabled "Allow executing file as program" checkbox from properties tab. Then I downloaded Minecraft 1.18.2 and 1.7.10 from Vlauncher's downloader and tried to launch the game but nothing happened. I also tried putting the launcher to a .minecraft folder that has been created by the official Minecraft launcher and tried launching the game from that folder and still, Vlauncher closed itself and nothing happened.

**Comment by Kron4ek** [comment]
Please launch the launcher from a terminal emulator, launch the game and show me the output from the terminal.

**Comment by 0xPascal** [comment]
```
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Unrecognized VM option 'CMSIncrementalMode'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
openjdk version "11.0.19" 2023-04-18
OpenJDK Runtime Environment (build 11.0.19+7-post-Ubuntu-0ubuntu122.04.1)
OpenJDK 64-Bit Server VM (build 11.0.19+7-post-Ubuntu-0ubuntu122.04.1, mixed mode, sharing)
```
There were no folder called crash-reports inside the folder containing Vlauncher.

**Comment by Kron4ek** [comment]
The problem is that your Java versions is unsuitable for these two versions. For 1.7.10 you need Java 8, and for 1.18.2 you need Java 17 or newer.
