### ISSUE TITLE
1.20 не запускается если что

### ISSUE THREAD

**Issue by f3f5-dev** [Kron4ek/minecraft-vortex-launcher#78]
а друг говорил что даже 1.19 нет

**Comment by f3f5-dev** [comment]
при нажатии мультиплеер вылетает только с этого лаунчера

**Comment by Kron4ek** [comment]
У меня запускается, я недавно проверял 1.20.1.

**Comment by f3f5-dev** [comment]
да, работает
видимо чет не то было

**Comment by f3f5-dev** [comment]
> У меня запускается, я недавно проверял 1.20.1.

а почему язык purebasic а не java тот же, контрибуторы страдать будут)

**Comment by Kron4ek** [comment]
> а почему язык purebasic а не java тот же, контрибуторы страдать будут)

Потому что проще чем Java.
