### ISSUE TITLE
Multiplayer Online(NOT LAN)

### ISSUE THREAD

**Issue by KOSMOSTARuzb** [Kron4ek/minecraft-vortex-launcher#79]
I want to play minecraft 1.16.5 with my friend.
Is there any way to do this online(not lan)?
If there are, leave a comment with instructions and/or link, please?

**Comment by Kron4ek** [comment]
There are at least three ways:

* Run [a dedicated server](https://www.minecraft.net/download/server) ([link](https://piston-data.mojang.com/v1/objects/1b557e7b033b583cd9f66746b7a9ab1ec1673ced/server.jar) for 1.16.5).
* Use a VPN that simulates LAN over the internet (like ZeroTier or similar).
* Use Minecraft server hosting. There are services that do that for free (search for "free minecraft server hosting").
