### ISSUE TITLE
1.17 1.19 1.20 error

### ISSUE THREAD

**Issue by ass42069** [Kron4ek/minecraft-vortex-launcher#87]
1.12.2 and older versions works fine but new version crash with this message
![image](https://github.com/Kron4ek/minecraft-vortex-launcher/assets/122709160/e05f6c78-f285-4c8b-9011-4bd3ad8bd8f3)

**Comment by Kron4ek** [comment]
What Java version are you using?

**Comment by ass42069** [comment]
i downloaded java17 and now everything works, wasnt reading sorry
