### ISSUE TITLE
Should add a way to put on skins

### ISSUE THREAD

**Issue by Desenplays** [Kron4ek/minecraft-vortex-launcher#88]
Shoul add a folder or something like that that inputs a skin to the game

**Comment by Johny-adri2** [comment]
Just use Fabric with CustomSkinLoader mod

**Comment by Desenplays** [comment]
@Johny-adri2 thanks for your response

**Comment by Dani3I** [comment]
> @Johny-adri2 thanks for your response,but how to play with fabric or mods, and I am on 1.20.6

- You download fabric from https://fabricmc.net
- Run downloaded file, select desired minecraft version and folder whrre vortex launcher is placed (vortex launcher does not installs minecraft into standard ".minecraft" location but instead files are just in the same place where vortex lanucher file is) and install.
- go to vortex launcher settings and select "Download missing libraries on game start" (you can try without this but I am not sure if it will work), then just start minecraft (with selected fabric version of minecraft 1.20.6) 
- close minecraft, folder called "mods" should apper in folder where vortex launcher is.
- put your mods into this folder and run minecraft.

So it is pretty standard installation except for the fact that you need to have selected "Download missing libraries on game start" (as it was responded here: https://github.com/Kron4ek/minecraft-vortex-launcher/issues/32#issuecomment-991618753 ) and remembering that your minecraft is not installed in "%appdata%\.minecraft". Other than that you should be able to follow any of the multiple tutorials that are presenting fabric (or forge) mod installation for minecraft.

**Comment by Desenplays** [comment]
@Dani3I Thank you very much!
