### ISSUE TITLE
java exception

### ISSUE THREAD

**Issue by Skylagged** [Kron4ek/minecraft-vortex-launcher#89]
![image](https://github.com/Kron4ek/minecraft-vortex-launcher/assets/173224088/e57d156a-3567-4c94-aa75-aea7d430b0bc)
everytime i try to use vortex after clicking play this just comes and closes itself

**Comment by Kron4ek** [comment]
What version of the game are you trying to run and what Java version are you using?

**Comment by Skylagged** [comment]
![image](https://github.com/Kron4ek/minecraft-vortex-launcher/assets/173224088/a097ce34-8390-409d-ade4-b279166e9730)
minecraft version 1.21

**Comment by Disa-Kizonda** [comment]
8 is too old for 1.21

**Comment by Skylagged** [comment]
then what do i use

**Comment by Disa-Kizonda** [comment]
https://adoptium.net/temurin/releases/?version=21&os=windows i use this

**Comment by Skylagged** [comment]
it works now, thanks
