### ISSUE TITLE
[Question] can you use mods with vortex launcher, and if yes, how?

### ISSUE THREAD

**Issue by Skylagged** [Kron4ek/minecraft-vortex-launcher#90]

**Comment by Skylagged** [comment]
sorry for no description i forgot to put in but like i said, can you install mods without needing things like curseforge? i know how to use texture packs but not mods.

**Comment by Dani3I** [comment]
> sorry for no description i forgot to put in but like i said, can you install mods without needing things like curseforge? i know how to use texture packs but not mods.

Here is simple steps to install fabric mods: https://github.com/Kron4ek/minecraft-vortex-launcher/issues/88#issuecomment-2132963941 . If tou want forge, the steps for should be the same (you just download forge instead of fabric instead).

**Comment by Skylagged** [comment]
doesnt work, it does install but mods dont work like just enough items

**Comment by Johny-adri2** [comment]
Really? Did you even install it properly?

> mods dont work like just enough items

**Comment by Skylagged** [comment]
yeah, I did

**Comment by Skylagged** [comment]
Yeah, I did

**Comment by Skylagged** [comment]
Nah but I don't need it anymore I actually bought minecraft now so I just use curse forge now
